{% set version = "1.0.2" %}


package:
  name: fs.sshfs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/fs.sshfs/fs.sshfs-{{ version }}.tar.gz
  sha256: 9a6a8567abf8925cd41d06a13c4af6097b48d0d0776fc7785a482a0428b0fc19

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - property-cached >=1.6,<1.7
    - fs >=2.4
    - paramiko >=2,<4
    - six >=1.10.0,<2

test:
  imports:
    - fs.sshfs

about:
  home: https://github.com/althonos/fs.sshfs
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: COPYING
  summary: Pyfilesystem2 over SSH using paramiko
  description: >
    Once created, the SSHFS filesystem behaves like any other filesystem see the Pyfilesystem2 documentation https://pyfilesystem2.readthedocs.io.

extra:
  recipe-maintainers:
    - ReimarBauer
    - althonos
