{% set version = "0.12.2" %}


package:
  name: fs.sshfs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/fs.sshfs/fs.sshfs-{{ version }}.tar.gz
  sha256: 4f7599c9c1e93f8351f3891b3a6e508781357d4c4c9afa87220105adca130f85

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - property-cached >=1.6,<1.7
    - configparser  # [py2k]
    - fs >=2.4
    - paramiko >=2,<3
    - six >=1.10.0,<2

test:
  imports:
    - fs.sshfs

about:
  home: https://github.com/althonos/fs.sshfs
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: COPYING
  summary: 'Pyfilesystem2 over SSH using paramiko'
  description: >
    Once created, the SSHFS filesystem behaves like any other filesystem
    see the Pyfilesystem2 documentation https://pyfilesystem2.readthedocs.io.

extra:
  recipe-maintainers:
    - ReimarBauer
