{% set version = "0.12.3" %}


package:
  name: fs.sshfs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/fs.sshfs/fs.sshfs-{{ version }}.tar.gz
  sha256: 909a08988591a90bea467f06dfff6463c3ca203de68e50052f1518cbfa6809fa

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - property-cached >=1.6,<1.7
    - fs >=2.4
    - paramiko >=2,<3
    - six >=1.10.0,<2

test:
  imports:
    - fs.sshfs

about:
  home: https://github.com/althonos/fs.sshfs
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: COPYING
  summary: Pyfilesystem2 over SSH using paramiko
  description: >
    Once created, the SSHFS filesystem behaves like any other filesystem see the Pyfilesystem2 documentation https://pyfilesystem2.readthedocs.io.

extra:
  recipe-maintainers:
    - ReimarBauer
