{% set name = "fs.sshfs" %}
{% set version = "0.11.1" %}
{% set sha256 = "8d761c295d23ddcf13d4ed6351548c3bc8013f8a49aa01fcfce119fda54a4610" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv" 

requirements:
  build:
    - python
    - setuptools
  host:
    - python
    - pip
  run:
    - python
    - cached-property >=1.5
    - six >=1.10.0,<2
    - paramiko >=2,<3
    - fs >=2.2.0,<2.4.0
    - configparser  # [py2k]

test:
  imports:
    - fs.sshfs

about:
  home: https://github.com/althonos/fs.sshfs
  license: LGPL v2.1
  license_family: LGPL
  license_file: COPYING
  summary: 'Pyfilesystem2 over SSH using paramiko'
  description: >
    Once created, the SSHFS filesystem behaves like any other filesystem
    see the Pyfilesystem2 documentation https://pyfilesystem2.readthedocs.io.

extra:
  recipe-maintainers:
    - ReimarBauer
