{% set version = "1.0.0" %}


package:
  name: fs.sshfs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/fs.sshfs/fs.sshfs-{{ version }}.tar.gz
  sha256: cf0c3675c325b4e988a093a4ad76b0eff37889ab57d6e1ea5788266875ac8278

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - property-cached >=1.6,<1.7
    - fs >=2.4
    - paramiko >=2,<3
    - six >=1.10.0,<2

test:
  imports:
    - fs.sshfs

about:
  home: https://github.com/althonos/fs.sshfs
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: COPYING
  summary: Pyfilesystem2 over SSH using paramiko
  description: >
    Once created, the SSHFS filesystem behaves like any other filesystem see the Pyfilesystem2 documentation https://pyfilesystem2.readthedocs.io.

extra:
  recipe-maintainers:
    - ReimarBauer
    - althonos
